# Generated by Django 4.2.16 on 2024-10-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_upload_project_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
