# Generated by Django 4.2.16 on 2024-10-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_timestamp_message_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="upload",
            name="keywords",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
