# Generated by Django 4.2.16 on 2024-11-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_project_category_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('MATH', 'Math'), ('SCIENCE', 'Science'), ('SOFTWARE', 'Software Development'), ('ENGLISH', 'English Literature'), ('MUSIC', 'Music'), ('ARTWORK', 'Artwork'), ('HISTORY', 'History'), ('PHYSICS', 'Physics'), ('CHEMISTRY', 'Chemistry'), ('BIOLOGY', 'Biology'), ('ENGINEERING', 'Engineering'), ('BUSINESS', 'Business'), ('ECONOMICS', 'Economics'), ('PHILOSOPHY', 'Philosophy'), ('PSYCHOLOGY', 'Psychology'), ('SOCIOLOGY', 'Sociology'), ('POLITICS', 'Politics'), ('LAW', 'Law'), ('MEDICINE', 'Medicine'), ('ARCHITECTURE', 'Architecture'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
