# Generated by Django 4.2.16 on 2024-11-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('ARCHITECTURE', 'Architecture'), ('ARTWORK', 'Artwork'), ('BIOLOGY', 'Biology'), ('BUSINESS', 'Business'), ('CHEMISTRY', 'Chemistry'), ('ECONOMICS', 'Economics'), ('ENGINEERING', 'Engineering'), ('ENGLISH', 'English Literature'), ('HISTORY', 'History'), ('LAW', 'Law'), ('MATH', 'Math'), ('MEDICINE', 'Medicine'), ('MUSIC', 'Music'), ('PHILOSOPHY', 'Philosophy'), ('PHYSICS', 'Physics'), ('POLITICS', 'Politics'), ('PSYCHOLOGY', 'Psychology'), ('SCIENCE', 'Science'), ('SOCIOLOGY', 'Sociology'), ('SOFTWARE', 'Software Development'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
    ]
