# Generated by Django 4.2.16 on 2024-11-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='number_of_reviewers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
