# Generated by Django 4.2.16 on 2024-11-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0011_alter_project_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "specializations",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="review_guidelines",
            field=models.FileField(
                blank=True, null=True, upload_to="review_guidelines/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="rubric",
            field=models.FileField(blank=True, null=True, upload_to="rubrics/"),
        ),
        migrations.AddConstraint(
            model_name="upload",
            constraint=models.UniqueConstraint(
                fields=("name", "project"), name="unique_upload_name_per_project"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
