# Generated by Django 4.2.16 on 2024-11-03 20:04

from django.db import migrations

def create_user_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('users', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_userprofile_project_review_guidelines_project_rubric_and_more"),
    ]

    operations = [
        migrations.RunPython(create_user_profiles),
    ]
