# Generated by Django 4.2.16 on 2024-11-03 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_project_is_private_project_number_of_reviewers'),
        ('users', '0013_auto_20241103_2004'),
    ]

    operations = [
    ]
