# Generated by Django 4.2.16 on 2024-11-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20241103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='transcription_job_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
