# Generated by Django 4.2.16 on 2024-11-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_upload_transcription_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='output_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
