# Generated by Django 4.2.16 on 2024-11-10 20:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_upload_output_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upvoters',
            field=models.ManyToManyField(blank=True, related_name='upvoted_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
