# Generated by Django 4.2.16 on 2024-11-15 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_project_upvoters_project_upvotes'),
        ('users', '0017_projectinvitation'),
    ]

    operations = [
    ]
