# Generated by Django 4.2.16 on 2024-11-17 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0018_merge_20241115_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, null=True),
            preserve_default=False,
        ),
    ]
