# Generated by Django 4.2.16 on 2024-11-21 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_upload_owner'),
        ('users', '0022_auto_20241121_1817'),
    ]

    operations = [
    ]
